# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hAIl Mary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hAIl Mary

  target 'hAIl MaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hAIl MaryUITests' do
    # Pods for testing
  end

end
